/************************************************************************************
 * FILE PURPOSE: Define the memory usage of the ibl module for the c6455
 ************************************************************************************
 * FILE NAME: ibl.cmd
 *
 * DESCRIPTION: The memory placement for the IBL is defined
 *
 ************************************************************************************/

/* In order to speed build time during debug, the object files are saved in
 * both big and little endian format. The include file is generated by
 * make to use the correct endian object files
 */
#include "ibl_objs.inc"


/* Symbols from the 1st portion of the load, generated by the make process */
#include "ibl_init_symbols.inc"

/* Common memory and section areas between ibl_init and ibl */
#include "ibl_common.inc"

SECTIONS
{
	.cinit  > TEXT
	.const  > TEXT
	.text   > TEXT
	.switch > TEXT
	.far    > DATA
	.bss    > DATA

}

