/* ibl_init_objs_template.inc
 *
 *  list of object files tagged with the endian field for replacement during make
 */

../main/c64x/make/iblinit.ENDIAN_TAG.oc
../main/c64x/make/ibliniti2c.ENDIAN_TAG.oc
../device/c64x/make/c6455init.ENDIAN_TAG.oc
../hw/c64x/make/pll.ENDIAN_TAG.oc
../hw/c64x/make/i2c.ENDIAN_TAG.oc
../interp/c64x/make/btblwrap.ENDIAN_TAG.oc
../interp/c64x/make/btblpr.ENDIAN_TAG.oc
../interp/c64x/make/gem.ENDIAN_TAG.oc






